name: Build and Test

on:
    workflow_call:
        inputs:
            target:
                description: the testing target
                required: true
                type: string
        secrets:
            CR_PAT:
                required: true

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-22.04
        container:
            image: ghcr.io/social-tw/ubuntu-circom:22.04
            credentials:
                username: jason-ntu
                password: ${{ secrets.CR_PAT }}
        timeout-minutes: 15
        steps:
            - name: Modify system variable PATH
              run: echo "/root/.cargo/bin" >> $GITHUB_PATH
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Install yarn
              run: npm install --global yarn
            - name: Install jest
              run: npm i --save-dev @types/jest
            - name: Clean and Install packages
              run: |
                  rm -rf node_modules package-lock.json
                  yarn
            - name: Install Hardhat locally
              run: yarn add --dev hardhat  --ignore-workspace-root-check
            - name: Build
              run: yarn build
            - name: Downcase target
              id: downcase
              uses: ASzc/change-string-case-action@v5
              with:
                  string: ${{ inputs.target }}
            - name: Test
              run: yarn ${{ steps.downcase.outputs.lowercase }} test
