name: Deploy
run-name: ${{ github.actor }} acitvates the actions 🚀

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3

            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: yarn

            - name: Install Tenderly CLI
              run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

            - name: Deploy contracts
              run: yarn contracts deploy:devnet
              env:
                  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
                  TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
                  TENDERLY_DEVNET_TEMPLATE: ${{ secrets.TENDERLY_DEVNET_TEMPLATE }}
                  TENDERLY_ACCOUNT_ID: ${{ secrets.TENDERLY_ACCOUNT_ID }}

            #- name: Deploy backend
            #  run:
            #  env:
            #      TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID}}
            #      TWITTER_CLIENT_KEY: ${{secrets.TWITTER_CLIENT_KEY}}

            #- name: Deploy frontend
            #  run:
